PATCH http://localhost:3000/posts
Content-Type: application/json

{
  "id": 7,
  "title": "Test title",
  "postType": "post",
  "status": "published",
  "content": "test content 1",
  "publishOn": "2024-03-16T07:46:32+0000",
  //"tags": ["nestjs", "typescript"],
  "metaOptions" : {
    "metaValue": "{ \"sidebarEnabled\": true, \"footerActive\": true }"
    },
  "tags": [1, 2]
}